language: ruby
cache: bundler
dist: trusty
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
before_install:
  - gem install bundler -v 1.17.3
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
script:
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
